name: netherite-scrap-plugin
version: @version@
description: An plugin for Spigot with Gradle
main: net.javaforge.minecraft.spigot.plugin.NetheriteScrapPlugin
authors : [Vincent, Paju]
depend: [WorldGuard, WGCustomFlags]
api-version: 1.16

commands:
  hello:
    description: say hello to the user
  tp:
    description: teleport to the spawn